### ISSUE TITLE
Switch to softwares suggestion

### ISSUE THREAD

**Issue by bwming** [qdore/Mutate#58] opened 2015-04-16 08:07 UTC
Mac didn't quit a software,it just hide it.So when i had opened an firefox explorer , opened another software and open Mutate to switch to the firefox,it just open a new firefox for me.Can we make a script that when I type switch ... it only reopen the old software for me instead of open a new one?We can make the Mutate to the software switching tool.

**Comment by codeThatThinks** [comment] 2015-04-26 19:05
This seems to be a duplicate of #19.

**Closed** 2015-04-26 19:06 UTC
Labels: duplicate
