### ISSUE TITLE
Bring already open windows to front without launching

### ISSUE THREAD

**Issue by chanakasan** [qdore/Mutate#29] opened 2015-01-17 15:57 UTC
Hi @qdore!,

Thanks for this great app. I was wondering if there's an option or some internal configuration that would allow me to bring an already open app to front without launching it again. The Alfred app does this and I really liked this feature in it. 

I'd really appreciate if you could give me some pointers on how to do this.

Thanks
Cheers!

**Comment by qdore** [comment] 2015-01-19 04:42
Okay, it's hard in Ubuntu but easy in mac, I will try to figure it out, thanks~

**Comment by jamesmackinnon** [comment] 2015-03-21 02:30
Just playing with ideas, but maybe it could be scripted with a combination of ps and wmctrl?

**Comment by codeThatThinks** [comment] 2015-04-26 19:09
Duplicate of #19.

**Closed by codeThatThinks** 2015-04-26 19:09 UTC
