### ISSUE TITLE
Install from AUR fails

### ISSUE THREAD

**Issue by joehillen** [qdore/Mutate#74] opened 2015-07-16 20:04 UTC
```
➤  sudo aura -A mutate-git
aura >>= Determining dependencies...
aura >>= Repository dependencies:
fcitx-qt5

aura >>= AUR Packages:
mutate-git

aura >>= Continue? [Y/n] 
resolving dependencies...
looking for conflicting packages...

Package (2)          New Version  Net Change  Download Size

community/fcitx      4.2.9-1       34.35 MiB       7.00 MiB
community/fcitx-qt5  1.0.3-1        0.36 MiB       0.09 MiB

Total Download Size:    7.09 MiB
Total Installed Size:  34.71 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages ...
 fcitx-4.2.9-1-x86_64                                                                                                                                                   7.0 MiB  5.68M/s 00:01 [#######################################################################################################################] 100%
 fcitx-qt5-1.0.3-1-x86_64                                                                                                                                              95.1 KiB  13.3M/s 00:00 [#######################################################################################################################] 100%
(2/2) checking keys in keyring                                                                                                                                                                 [#######################################################################################################################] 100%
(2/2) checking package integrity                                                                                                                                                               [#######################################################################################################################] 100%
(2/2) loading package files                                                                                                                                                                    [#######################################################################################################################] 100%
(2/2) checking for file conflicts                                                                                                                                                              [#######################################################################################################################] 100%
(2/2) checking available disk space                                                                                                                                                            [#######################################################################################################################] 100%
(1/2) installing fcitx                                                                                                                                                                         [#######################################################################################################################] 100%
You should at least install one of kcm-fcitx (For Qt/KDE users) or fcitx-configtool (For GTK+ users) to enable Fcitx configuration GUI.
Optional dependencies for fcitx
    enchant: for word predication support [installed]
    opencc: optional engine to do chinese convert
    gettext: for fcitx-po-parser [installed]
(2/2) installing fcitx-qt5                                                                                                                                                                     [#######################################################################################################################] 100%
aura >>= Building `mutate-git`...
aura >>= Well, building `mutate-git` failed.
aura >>= Dumping makepkg output in 3.. 2.. 1..
==> Making package: mutate-git 56-1 (Thu Jul 16 13:02:52 PDT 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning Mutate git repo...
Cloning into bare repository '/var/cache/pacman/pkg/mutate-git1667/mutate-git/Mutate'...
==> Validating source files with md5sums...
    Mutate ... Skipped
==> Extracting sources...
  -> Creating working copy of Mutate git repo...
Cloning into 'Mutate'...
done.
==> Starting pkgver()...
==> Updated version: mutate-git 73-1
==> Starting build()...
qtsinglecoreapplication/qtlocalpeer.cpp: In member function ‘bool QtLocalPeer::sendMessage(const QString&, int)’:
qtsinglecoreapplication/qtlocalpeer.cpp:160:19: error: variable ‘QDataStream ds’ has initializer but incomplete type
     QDataStream ds(&socket);
                   ^
qtsinglecoreapplication/qtlocalpeer.cpp: In member function ‘void QtLocalPeer::receiveConnection()’:
qtsinglecoreapplication/qtlocalpeer.cpp:180:26: error: variable ‘QDataStream ds’ has initializer but incomplete type
     QDataStream ds(socket);
                          ^
make: *** [qtlocalpeer.o] Error 1
==> ERROR: A failure occurred in build().
    Aborting...

/usr/lib/qt/bin/uic widget.ui -o ui_widget.h
/usr/lib/qt/bin/uic setting.ui -o ui_setting.h
/usr/lib/qt/bin/uic hotkey.ui -o ui_hotkey.h
/usr/lib/qt/bin/uic listitem.ui -o ui_listitem.h
/usr/lib/qt/bin/uic doublelistitem.ui -o ui_doublelistitem.h
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -pthread -pthread -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_X11EXTRAS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -Iqxtglobalshortcut -Iqtsinglecoreapplication -I../include -isystem /usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -isystem /usr/include/pango-1.0 -isystem /usr/include/atk-1.0 -isystem /usr/include/cairo -isystem /usr/include/pixman-1 -isystem /usr/include/libdrm -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/libpng16 -isystem /usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -isystem /usr/include/freetype2 -isystem /usr/include/harfbuzz -isystem /usr/include/qt -isystem /usr/include/qt/QtX11Extras -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o qxtglobalshortcut.o qxtglobalshortcut/qxtglobalshortcut.cpp
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -pthread -pthread -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_X11EXTRAS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -Iqxtglobalshortcut -Iqtsinglecoreapplication -I../include -isystem /usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -isystem /usr/include/pango-1.0 -isystem /usr/include/atk-1.0 -isystem /usr/include/cairo -isystem /usr/include/pixman-1 -isystem /usr/include/libdrm -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/libpng16 -isystem /usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -isystem /usr/include/freetype2 -isystem /usr/include/harfbuzz -isystem /usr/include/qt -isystem /usr/include/qt/QtX11Extras -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o qxtglobalshortcut_x11.o qxtglobalshortcut/qxtglobalshortcut_x11.cpp
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -pthread -pthread -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_X11EXTRAS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -Iqxtglobalshortcut -Iqtsinglecoreapplication -I../include -isystem /usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -isystem /usr/include/pango-1.0 -isystem /usr/include/atk-1.0 -isystem /usr/include/cairo -isystem /usr/include/pixman-1 -isystem /usr/include/libdrm -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/libpng16 -isystem /usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -isystem /usr/include/freetype2 -isystem /usr/include/harfbuzz -isystem /usr/include/qt -isystem /usr/include/qt/QtX11Extras -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o qtsinglecoreapplication.o qtsinglecoreapplication/qtsinglecoreapplication.cpp
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -pthread -pthread -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_X11EXTRAS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -Iqxtglobalshortcut -Iqtsinglecoreapplication -I../include -isystem /usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -isystem /usr/include/pango-1.0 -isystem /usr/include/atk-1.0 -isystem /usr/include/cairo -isystem /usr/include/pixman-1 -isystem /usr/include/libdrm -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/libpng16 -isystem /usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -isystem /usr/include/freetype2 -isystem /usr/include/harfbuzz -isystem /usr/include/qt -isystem /usr/include/qt/QtX11Extras -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o qtlocalpeer.o qtsinglecoreapplication/qtlocalpeer.cpp
Makefile:765: recipe for target 'qtlocalpeer.o' failed

aura >>= Would you like to continue anyway? [Y/n] 
```

**Comment by michaldarda** [comment] 2015-07-17 21:12
Yeah, I've got this too, and when compiling on 64bit arch I got this error (during make)

```
qtsinglecoreapplication/qtlocalpeer.cpp: In member function ‘void QtLocalPeer::receiveConnection()’:
qtsinglecoreapplication/qtlocalpeer.cpp:180:26: error: variable ‘QDataStream ds’ has initializer but incomplete type
     QDataStream ds(socket);
                          ^
Makefile:771: recipe for target 'qtlocalpeer.o' failed
make: *** [qtlocalpeer.o] Error 1


```

**Comment by bjorntj** [comment] 2015-07-21 08:59
Yes, the following include is missing in qtlocalpeer.cpp:

#include <QtCore/QDataStream>

**Comment by myhau** [comment] 2015-07-22 22:57
Got that too, any workarounds ?

**Comment by codeThatThinks** [comment] 2015-07-23 01:07
The issue is that  the latest version of Qt5 breaks qtsinglecoreapplication. Not sure if it has been fixed in a new version of qtsinglecoreapp. The version we're using is 10 months old.

**Comment by bjorntj** [comment] 2015-07-23 04:27
The workaround is to include the missing include in qtlocalpeer.cpp, as I said... :)

**Closed** 2015-07-27 17:09 UTC
